# Generated by Django 5.2 on 2025-05-07 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_apartment_hotel_name_remove_hotel_hotel_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='apartment_owner',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='hotel_address',
        ),
    ]
