# Generated by Django 5.2 on 2025-05-07 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_apartment_apartment_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='hotel',
            new_name='hotel_name',
        ),
    ]
