# Generated by Django 5.2 on 2025-05-08 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_reviews_rating_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentimages',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_connect_apartment', to='booking.apartment'),
        ),
        migrations.AlterField(
            model_name='hotelimages',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_connect_hotel', to='booking.hotel'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.country'),
        ),
    ]
