# Generated by Django 5.2 on 2025-05-08 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_remove_userprofile_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.country'),
            preserve_default=False,
        ),
    ]
