# Generated by Django 5.2 on 2025-05-08 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_userprofile_user_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_country',
        ),
    ]
