# Generated by Django 5.2 on 2025-05-08 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_remove_userprofile_user_country'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviews',
            unique_together={('review_author', 'hotel')},
        ),
    ]
