# Generated by Django 5.2 on 2025-05-12 07:10

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_alter_reviews_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicecity',
            name='flag_country',
            field=models.ImageField(null=True, upload_to='country_flag/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='hotel',
            name='rating_stars',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='apartment_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating_stars',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')]),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review_text',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review_text_en',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review_text_es',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review_text_ru',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.favorite')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_bonus', models.ImageField(upload_to='icon_bonuses')),
                ('name_bonus', models.CharField(max_length=50)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.hotel')),
            ],
        ),
    ]
