# Generated by Django 5.2 on 2025-05-07 15:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_image', models.ImageField(upload_to='')),
                ('user_age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)])),
                ('user_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('account_created_date', models.DateField(auto_now_add=True)),
                ('user_country', models.CharField(max_length=100)),
                ('guest_status', models.CharField(choices=[('owner', 'owner'), ('guest', 'guest')], default='guest')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100)),
                ('hotel_address', models.CharField(max_length=100, unique=True)),
                ('apartment_number', models.PositiveSmallIntegerField()),
                ('apartment_type', models.CharField(choices=[('studio', 'studio'), ('one_bedroom', 'one_bedroom'), ('two_bedroom', 'two_bedroom'), ('luxury', 'luxury'), ('penthouse', 'penthouse'), ('loft', 'loft'), ('serviced', 'serviced'), ('duplex', 'duplex'), ('townhouse', 'townhouse'), ('residence', 'residence')])),
                ('video_file', models.FileField(blank=True, null=True, upload_to='apartment_videos/')),
                ('apartment_description', models.TextField(max_length=500)),
                ('apartment_description_en', models.TextField(max_length=500, null=True)),
                ('apartment_description_ru', models.TextField(max_length=500, null=True)),
                ('apartment_description_es', models.TextField(max_length=500, null=True)),
                ('is_free', models.CharField(choices=[('available', 'available'), ('reserved', 'reserved'), ('occupied', 'occupied')], default='available')),
                ('all_service', models.BooleanField(default=True)),
                ('apartment_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('apartment_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_image', models.ImageField(blank=True, null=True, upload_to='apartment_images/')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.apartment')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.country')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_country', models.FileField(upload_to='country_images/')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.country')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100)),
                ('hotel_address', models.CharField(max_length=100, unique=True)),
                ('hotel_description', models.TextField(max_length=200)),
                ('hotel_description_en', models.TextField(max_length=200, null=True)),
                ('hotel_description_ru', models.TextField(max_length=200, null=True)),
                ('hotel_description_es', models.TextField(max_length=200, null=True)),
                ('hotel_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('hotel_stars', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('choice_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.choicecity')),
                ('hotel_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('apartment_reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.apartment')),
                ('user_reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hotel_reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.hotel')),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.hotel'),
        ),
        migrations.CreateModel(
            name='HotelImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_image', models.ImageField(blank=True, null=True, upload_to='hotel_images/')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(max_length=200)),
                ('review_text_en', models.TextField(max_length=200, null=True)),
                ('review_text_ru', models.TextField(max_length=200, null=True)),
                ('review_text_es', models.TextField(max_length=200, null=True)),
                ('rating_stars', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.hotel')),
                ('review_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
