# Generated by Django 5.2 on 2025-05-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_alter_userprofile_user_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='guest_status',
            field=models.CharField(choices=[('admin', 'admin'), ('owner', 'owner'), ('guest', 'guest')], default='guest'),
        ),
    ]
