# Generated by Django 5.2 on 2025-05-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_alter_userprofile_guest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='hotel_name',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_price',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_stars',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_description_en',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_description_es',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_description_ru',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
