# Generated by Django 5.2 on 2025-05-07 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_rename_hotel_apartment_hotel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_connect_apartment', to='mysite.hotel'),
        ),
    ]
