# Generated by Django 5.2 on 2025-05-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_reviews_apartment_alter_reviews_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='guest_status',
            field=models.CharField(choices=[('owner', 'owner'), ('guest', 'guest')], default='guest'),
        ),
    ]
