# Generated by Django 5.2 on 2025-05-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_alter_userprofile_guest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rating_stars',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
