# Generated by Django 5.2 on 2025-05-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_alter_apartmentimages_apartment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_country',
            field=models.CharField(max_length=100),
        ),
    ]
